### PR TITLE
Add native Compose Navigator

### LINKED ISSUE #13: Question: Multiple compose backstacks supported
I don't see any examples regarding this. Is simple-stack-compose-integration designed with multiple compose backstack support? For example, I'd like an outer backstack closer to the activity level and I'd also like a backstack contained within a BottomSheetScaffold. Before I spend time on a sizeable prototype I was hoping you could either say  yes, no, or maybe yes with caveats. This will be greenfield development, no fragments, views, etc.

### PR DESCRIPTION
**Pull request by matejdro**
PR adds a version of the `Navigator`, written entirely in Compose (instead of using fragment-based Navigator). It uses its own ViewModel to store backstack and services.

This has two benefits:

* It makes initialization of the stack much easier, since there is no need to deal with Navigator fragment. All initialization is done in 100% compose
* Since everything is done in Compose, this makes nesting backstacks trivial. You can just call  `ComposeNavigator` composable inside a screen and you create a nested backstack (I've included an example of this in the second commit).

Main drawback here is, that in order to support nested navigation, this Navigator must also handle back button events natively. Unfortuantely, current design of simple-stack does not allow full functionality for this (as discussed in https://github.com/Zhuinden/simple-stack/issues/259). Current implementation works for basic navigation, but it omits support for `ScopedServices.HandlesBack`. If desired, I can mark this PR as Draft and we can wait until you figure out how to tackle that.

This fixes #13

### CODE REVIEW

**Comment by matejdro** [comment]
It might be a good idea to do a bit more extensive testing on this or maybe mark it as experimental until we are sure it works reliably. I've already found two issues and fixed them.

**Comment by Zhuinden** [comment]
I want to make better BackHandler integration before merging this, but this initiative is amazing nonetheless. 👀

**Comment by matejdro** [comment]
Taking another look at the code, do we still need to detach and re-attach state changer on resume/pause? This defers first navigation to after activity reaches the resumed state.

I can't think of specific issues with that off the top of my head, but knowing Android's lifecycle, I'm sure there are some.

**Comment by Zhuinden** [comment]
> Taking another look at the code, do we still need to detach and re-attach state changer on resume/pause? This defers first navigation to after activity reaches the resumed state.
> 
> I can't think of specific issues with that off the top of my head, but knowing Android's lifecycle, I'm sure there are some.

Something about dialogs. Runtime permission dialog I know makes your app go to onPause.

I finally got the "I'll look at it next week" about a month later, now the samples handle onBackInvokedCallback.

When opting into `setBackHandlingModel(AHEAD_OF_TIME)`, `ScopedServices.HandlesBack` is no longer called.

**Comment by matejdro** [comment]
Okay, but is there any reason to detach state changer whenever a dialog pops up over our app?

How should we proceed with this PR, now that we have new back handling model? Should we just add an assertion to ensure this composable is only used when back handling model is set to AHEAD_OF_TIME?

**Comment by Zhuinden** [comment]
> Okay, but is there any reason to detach state changer whenever a dialog pops up over our app?
> 
> How should we proceed with this PR, now that we have new back handling model? Should we just add an assertion to ensure this composable is only used when back handling model is set to AHEAD_OF_TIME?

I was thinking about this, and I eventually didn't expose `backstack.getBackHandlingModel()` because it messes with the api surface. 

While I'm not 100% happy with the idea (I probably should have exposed it anyway), we can still detect the set model by catching the exception coming from `willHandleAheadOfTimeBack()` when the model isn't set. It just returns the current value of the boolean so it's effectively free when it's set. 

---

Detaching the state changer ensures some kind of behavior regarding the system permission dialog and commitNow(). And it's also there so that the app is resumed before trying to navigate. Honestly, I ran into the issue quite long ago, unless I'm imagining things and this came directly from square/Flow InternalLifecycleIntegration.

**Comment by matejdro** [comment]
Updated PR to use new back handling system.

This leaves `Backstack.historyAsState()` composable function unused, but I have decided to not delete it as it might be useful to the end user. What do you think?

**Comment by Zhuinden** [comment]
I see no bug. 👍

**Comment by Zhuinden** [comment]
@matejdro This is a super powerful addition, however during testing, I found https://github.com/Zhuinden/simple-stack-compose-integration/issues/26 .

I will hopefully look at it later, however maybe you can see the cause sooner than I do?

**Comment by Zhuinden** [comment]
(nvm I figured it out, I'll fix it when I get back home)

**Pull request merged**
